#!/usr/bin/env python3

import time
from pathlib import Path

LO_TEMP = 55
HI_TEMP = 70
HYSTERESIS = 5

LO_SPEED = 10
HI_SPEED = 100

PERIOD = 40000  # ns
PWM = "/sys/class/pwm/pwmchip0/pwm0"

current_speed = 0

def write(path, value):
    with open(path, "w") as file:
        file.write(str(value))

def init():
    if not Path(PWM).exists():
        write("/sys/class/pwm/pwmchip0/export", 0)
        time.sleep(0.1)

    write(f"{PWM}/period", PERIOD)
    write(f"{PWM}/polarity", "normal")
    write(f"{PWM}/enable", 1)
    write(f"{PWM}/duty_cycle", 0)

def read_temp():
    with open("/sys/devices/virtual/thermal/thermal_zone0/temp", "r") as file:
        return int(file.read()) / 1000

def set_fanspeed(speed_percent):
    duty = int(PERIOD * speed_percent / 100)
    write(f"{PWM}/duty_cycle", duty)

def calc_fanspeed(temp):
    global current_speed

    if temp > HI_TEMP:
        current_speed = HI_SPEED
    elif temp > HI_TEMP - HYSTERESIS and current_speed == HI_SPEED:
        pass
    elif temp > LO_TEMP:
        current_speed = LO_SPEED
    elif temp > LO_TEMP - HYSTERESIS and current_speed == LO_SPEED:
        pass
    else:
        current_speed = 0

    return current_speed

if not Path(f"{PWM}/duty_cycle").exists():
    init()

while True:
    temp = read_temp()
    speed = calc_fanspeed(temp)
    set_fanspeed(speed)
    time.sleep(2)
